language: go

go:
- '1.12'

env:
  - GO111MODULE=on

os: linux

install:
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go mod vendor

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_pull_requests.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_non_pull_requests.sh; fi'
